/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutModalDialog: typeof import('./src/components/modal/AboutModalDialog.vue')['default']
    AuthorGlyph: typeof import('./src/components/AuthorGlyph.vue')['default']
    AuthorModalDialog: typeof import('./src/components/modal/AuthorModalDialog.vue')['default']
    BoostKeywordsComponent: typeof import('./src/components/BoostKeywordsComponent.vue')['default']
    CompactButton: typeof import('./src/components/basic/CompactButton.vue')['default']
    CompactSwitch: typeof import('./src/components/basic/CompactSwitch.vue')['default']
    ConfirmDialog: typeof import('./src/components/basic/ConfirmDialog.vue')['default']
    ErrorToast: typeof import('./src/components/basic/ErrorToast.vue')['default']
    ExcludedModalDialog: typeof import('./src/components/modal/ExcludedModalDialog.vue')['default']
    FilterMenuComponent: typeof import('./src/components/FilterMenuComponent.vue')['default']
    HeaderExternalLinks: typeof import('./src/components/HeaderExternalLinks.vue')['default']
    HeaderPanel: typeof import('./src/components/HeaderPanel.vue')['default']
    InfoDialog: typeof import('./src/components/basic/InfoDialog.vue')['default']
    InlineIcon: typeof import('./src/components/basic/InlineIcon.vue')['default']
    KeyboardControlsModalDialog: typeof import('./src/components/modal/KeyboardControlsModalDialog.vue')['default']
    LazyPublicationComponent: typeof import('./src/components/LazyPublicationComponent.vue')['default']
    ModalDialog: typeof import('./src/components/modal/ModalDialog.vue')['default']
    NetworkControls: typeof import('./src/components/NetworkControls.vue')['default']
    NetworkHeader: typeof import('./src/components/NetworkHeader.vue')['default']
    NetworkVisComponent: typeof import('./src/components/NetworkVisComponent.vue')['default']
    PublicationComponent: typeof import('./src/components/PublicationComponent.vue')['default']
    PublicationComponentSearch: typeof import('./src/components/PublicationComponentSearch.vue')['default']
    PublicationDescription: typeof import('./src/components/PublicationDescription.vue')['default']
    PublicationListComponent: typeof import('./src/components/PublicationListComponent.vue')['default']
    PublicationTag: typeof import('./src/components/PublicationTag.vue')['default']
    QueueModalDialog: typeof import('./src/components/modal/QueueModalDialog.vue')['default']
    QuickAccessBar: typeof import('./src/components/QuickAccessBar.vue')['default']
    SearchModalDialog: typeof import('./src/components/modal/SearchModalDialog.vue')['default']
    SelectedPublicationsComponent: typeof import('./src/components/SelectedPublicationsComponent.vue')['default']
    SessionMenuComponent: typeof import('./src/components/SessionMenuComponent.vue')['default']
    SuggestedPublicationsComponent: typeof import('./src/components/SuggestedPublicationsComponent.vue')['default']
  }
}
